//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Guest_Reporting_System
{


    public partial class register
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Hotel_Guest_Reporting_System.Site Master
        {
            get
            {
                return ((Hotel_Guest_Reporting_System.Site)(base.Master));
            }
        }
    }
}
