//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceWebsiteB2B {
    
    
    public partial class error {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new EcommerceWebsiteB2B.Main Master {
            get {
                return ((EcommerceWebsiteB2B.Main)(base.Master));
            }
        }
    }
}
